#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The factory Musical Worlds as a C header (tools/build.py generate(), also with --gen-only):

  tools/gen_worlds.py build/gen/felucca_worlds.h [--src worlds/factory]

Compiles every worlds/factory/*.world.json with tools/worldc.py (static checks only, the factory size limit),
sorts the Worlds by category, then name, and writes WORLD_NFACTORY, WORLD_DATA (the blobs back to back, each
4-byte aligned) and WORLD_INDEX ({world_id, offset, length}). Any error fails the build. With no factory World
the header is still valid (WORLD_NFACTORY 0). The file is only rewritten when its contents change.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import worldc  # noqa: E402


def build(src_dir):
    worlds, failed = [], False
    for path in sorted(Path(src_dir).glob("*.world.json")):
        src = worldc.load_json(path)
        blob, d = worldc.compile_world(src)
        worldc.report(str(path), d)
        if blob is None:
            failed = True
            continue
        meta = worldc.decode(blob)["meta"]
        worlds.append({"path": path, "id": src.get("id"), "hash": worldc.decode(blob)["id_hash"], "blob": blob,
                       "name": meta["name"], "cat": meta["cat"]})
    if failed:
        raise SystemExit("gen_worlds: a factory World failed to compile")
    seen = {}
    for w in worlds:
        if w["hash"] in seen:
            raise SystemExit(f"gen_worlds: {w['path'].name} and {seen[w['hash']].name}: the same device id "
                             f"{w['hash']:#010x} (ids {w['id']!r}, FNV-1a collision or a duplicate id)")
        seen[w["hash"]] = w["path"]
    worlds.sort(key=lambda w: (w["cat"], w["name"], w["id"]))
    return worlds


def header(worlds):
    out = ["/* generated by tools/gen_worlds.py from the World sources in worlds/factory: do not edit */",
           "#ifndef FELUCCA_WORLDS_H", "#define FELUCCA_WORLDS_H",
           f"#define WORLD_NFACTORY {len(worlds)}"]
    data, index = bytearray(), []
    for w in worlds:
        data += b"\0" * (-len(data) % 4)
        index.append((w["hash"], len(data), len(w["blob"]), w))
        data += w["blob"]
    out.append(f"#define WORLD_DATA_LEN {len(data)}")
    out.append("typedef struct { uint32_t id; uint16_t off, len; } world_index_t;")
    out.append(f"static const uint8_t WORLD_DATA[{max(1, len(data))}] __attribute__((aligned(4))) = {{")
    if not data:
        out.append("    0")
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(f"0x{x:02x}" for x in data[i:i + 16]) + ",")
    out.append("};")
    out.append(f"static const world_index_t WORLD_INDEX[{max(1, len(index))}] = {{")
    if not index:
        out.append("    {0, 0, 0}")
    for h, off, ln, w in index:
        out.append(f"    {{0x{h:08x}u, {off}, {ln}}},   /* {json.dumps(w['name'])} ({w['cat']}): {w['path'].name} */")
    out.append("};")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main(argv):
    if not argv or argv[0].startswith("-"):
        raise SystemExit(__doc__)
    out = Path(argv[0])
    src = worldc.ROOT / "worlds" / "factory"
    if len(argv) == 3 and argv[1] == "--src":
        src = Path(argv[2])
    worlds = build(src)
    text = header(worlds)
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    total = sum(len(w["blob"]) for w in worlds)
    print(f"felucca_worlds.h: {len(worlds)} factory World(s), {total} B" +
          "".join(f"\n  {w['cat']:<10} {w['name']:<14} {len(w['blob'])} B" for w in worlds))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
